// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRoomMemberData.proto

#include "ChatRoomMemberData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR ChatRoomMemberData::ChatRoomMemberData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.memberlist_)*/{}
  , /*decltype(_impl_.field_4_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.membercount_)*/0
  , /*decltype(_impl_.infomask_)*/0
  , /*decltype(_impl_.field_5_)*/0
  , /*decltype(_impl_.field_7_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChatRoomMemberDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatRoomMemberDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatRoomMemberDataDefaultTypeInternal() {}
  union {
    ChatRoomMemberData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatRoomMemberDataDefaultTypeInternal _ChatRoomMemberData_default_instance_;

// ===================================================================

class ChatRoomMemberData::_Internal {
 public:
};

void ChatRoomMemberData::clear_memberlist() {
  _impl_.memberlist_.Clear();
}
ChatRoomMemberData::ChatRoomMemberData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ChatRoomMemberData)
}
ChatRoomMemberData::ChatRoomMemberData(const ChatRoomMemberData& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  ChatRoomMemberData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.memberlist_){from._impl_.memberlist_}
    , decltype(_impl_.field_4_){}
    , decltype(_impl_.membercount_){}
    , decltype(_impl_.infomask_){}
    , decltype(_impl_.field_5_){}
    , decltype(_impl_.field_7_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.field_4_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.field_4_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_field_4().empty()) {
    _this->_impl_.field_4_.Set(from._internal_field_4(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.membercount_, &from._impl_.membercount_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.field_7_) -
    reinterpret_cast<char*>(&_impl_.membercount_)) + sizeof(_impl_.field_7_));
  // @@protoc_insertion_point(copy_constructor:ChatRoomMemberData)
}

inline void ChatRoomMemberData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.memberlist_){arena}
    , decltype(_impl_.field_4_){}
    , decltype(_impl_.membercount_){0}
    , decltype(_impl_.infomask_){0}
    , decltype(_impl_.field_5_){0}
    , decltype(_impl_.field_7_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.field_4_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.field_4_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ChatRoomMemberData::~ChatRoomMemberData() {
  // @@protoc_insertion_point(destructor:ChatRoomMemberData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChatRoomMemberData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.memberlist_.~RepeatedPtrField();
  _impl_.field_4_.Destroy();
}

void ChatRoomMemberData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChatRoomMemberData::Clear() {
// @@protoc_insertion_point(message_clear_start:ChatRoomMemberData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.memberlist_.Clear();
  _impl_.field_4_.ClearToEmpty();
  ::memset(&_impl_.membercount_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.field_7_) -
      reinterpret_cast<char*>(&_impl_.membercount_)) + sizeof(_impl_.field_7_));
  _internal_metadata_.Clear<std::string>();
}

const char* ChatRoomMemberData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 memberCount = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.membercount_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .ChatRoomMemberInfo memberList = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_memberlist(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // int32 InfoMask = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.infomask_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string field_4 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_field_4();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // int32 field_5 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.field_5_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 field_7 = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.field_7_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChatRoomMemberData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ChatRoomMemberData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 memberCount = 1;
  if (this->_internal_membercount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_membercount(), target);
  }

  // repeated .ChatRoomMemberInfo memberList = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_memberlist_size()); i < n; i++) {
    const auto& repfield = this->_internal_memberlist(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // int32 InfoMask = 3;
  if (this->_internal_infomask() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_infomask(), target);
  }

  // string field_4 = 4;
  if (!this->_internal_field_4().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_field_4().data(), static_cast<int>(this->_internal_field_4().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ChatRoomMemberData.field_4");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_field_4(), target);
  }

  // int32 field_5 = 5;
  if (this->_internal_field_5() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_field_5(), target);
  }

  // int32 field_7 = 7;
  if (this->_internal_field_7() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_field_7(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ChatRoomMemberData)
  return target;
}

size_t ChatRoomMemberData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ChatRoomMemberData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ChatRoomMemberInfo memberList = 2;
  total_size += 1UL * this->_internal_memberlist_size();
  for (const auto& msg : this->_impl_.memberlist_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string field_4 = 4;
  if (!this->_internal_field_4().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_field_4());
  }

  // int32 memberCount = 1;
  if (this->_internal_membercount() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_membercount());
  }

  // int32 InfoMask = 3;
  if (this->_internal_infomask() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_infomask());
  }

  // int32 field_5 = 5;
  if (this->_internal_field_5() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_field_5());
  }

  // int32 field_7 = 7;
  if (this->_internal_field_7() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_field_7());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ChatRoomMemberData::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const ChatRoomMemberData*>(
      &from));
}

void ChatRoomMemberData::MergeFrom(const ChatRoomMemberData& from) {
  ChatRoomMemberData* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:ChatRoomMemberData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.memberlist_.MergeFrom(from._impl_.memberlist_);
  if (!from._internal_field_4().empty()) {
    _this->_internal_set_field_4(from._internal_field_4());
  }
  if (from._internal_membercount() != 0) {
    _this->_internal_set_membercount(from._internal_membercount());
  }
  if (from._internal_infomask() != 0) {
    _this->_internal_set_infomask(from._internal_infomask());
  }
  if (from._internal_field_5() != 0) {
    _this->_internal_set_field_5(from._internal_field_5());
  }
  if (from._internal_field_7() != 0) {
    _this->_internal_set_field_7(from._internal_field_7());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void ChatRoomMemberData::CopyFrom(const ChatRoomMemberData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ChatRoomMemberData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChatRoomMemberData::IsInitialized() const {
  return true;
}

void ChatRoomMemberData::InternalSwap(ChatRoomMemberData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.memberlist_.InternalSwap(&other->_impl_.memberlist_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.field_4_, lhs_arena,
      &other->_impl_.field_4_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ChatRoomMemberData, _impl_.field_7_)
      + sizeof(ChatRoomMemberData::_impl_.field_7_)
      - PROTOBUF_FIELD_OFFSET(ChatRoomMemberData, _impl_.membercount_)>(
          reinterpret_cast<char*>(&_impl_.membercount_),
          reinterpret_cast<char*>(&other->_impl_.membercount_));
}

std::string ChatRoomMemberData::GetTypeName() const {
  return "ChatRoomMemberData";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ChatRoomMemberData*
Arena::CreateMaybeMessage< ::ChatRoomMemberData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ChatRoomMemberData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
